#!/usr/bin/env python3

def myhex(bitstring):
    return hex(int(bitstring, 2))[2:].rjust(2, "0").upper()

leftdata = [ [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [] ]
rightdata = [ [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [] ]
with open("font.txt", "r") as f:
    for c in 'ABCDEFGHJIKLMNOPQRSTUVWXY':
        #print(c)
        for row in range(16):
            left = f.read(7)
            right = f.read(7)
            f.readline()
            left = "0b1" + left[::-1]
            right = "0b1" + right[::-1]
            #print(myhex(left), myhex(right))
            leftdata[row].append(myhex(left))
            rightdata[row].append(myhex(right))
print("; Curious Fred pixel font (abridged)")
print("; (c) 2022 by 4am")
print("; license:Open Font License 1.1, see OFL.txt")
print("; This file is automatically generated")
for row in range(1,15):
    print("LeftFontRow%s" % row)
    for c, i in zip(leftdata[row], range(len(leftdata[row]))):
        print("         !byte $%s        ; %s" % (c, chr(i+65)))
for row in range(1,15):
    print("RightFontRow%s" % row)
    for c, i in zip(rightdata[row], range(len(rightdata[row]))):
        print("         !byte $%s        ; %s" % (c, chr(i+65)))
